language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t klaudiuszkudla/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true klaudiuszkudla/react-test npm test

after_success:
  - docker build -t klaudiuszkudla/multi-client ./client
  - docker build -t klaudiuszkudla/multi-nginx ./nginx
  - docker build -t klaudiuszkudla/multi-server ./server
  - docker build -t klaudiuszkudla/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push klaudiuszkudla/multi-client
  - docker push klaudiuszkudla/multi-nginx
  - docker push klaudiuszkudla/multi-server
  - docker push klaudiuszkudla/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-north-1-851725555123
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY